### ISSUE TITLE
Improve the schema and the interface for capturing the Scan Results 

### ISSUE THREAD

**Issue by skounis** [skounis/eu-dcc-validation#13]
## Input

3. [x] Identify the meta data for supporting the collected results

## Task
1. [x] Improve the Schema https://github.com/skounis/eu-dcc-validation/pull/27
    According https://github.com/skounis/eu-dcc-validation#result-format
2. [x] Align the interfaces
