### ISSUE TITLE
Decorate the QR Codes - Communication validation status 

### ISSUE THREAD

**Issue by skounis** [skounis/eu-dcc-validation#42]
While users are browsing and validating QR codes, the application should communicate the status of each and the overall progress:
1. Number of validations pending 
2. Number of validations submitted 
3. QR outcome submitted. 
## Tasks
1. [x] Scaffold the UX 
2. [x] Implement and apply a decorator to the QR Codes displayed 
3. [x] Provide summary and progress details.
